# Notebook to get graph and plot to insert in DeepFew Proposal

## Preamble

We investigate the distribution of alphas and distances in the specific case of He trimer with a simple Gaussian Potential

In [1]:
import numpy as np
import scipy as sp
import math
import h5py

import matplotlib
#matplotlib.use('Agg')
from mpl_toolkits import mplot3d
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import itertools
from matplotlib import cm
from matplotlib import rc
#rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
## for Palatino and other serif fonts use:
rc('font',**{'family':'serif','serif':['Palatino']})
rc('text', usetex=True)
%load_ext autoreload
%autoreload 2
from IPython import get_ipython
# get_ipython().run_line_magic('matplotlib', 'qt')

from numpy import random
from scipy import linalg
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform
# from sklearn.decomposition import PCA
# from sklearn.preprocessing import StandardScaler

f = h5py.File("prova_random_gauss_6.h5")

In [20]:
A = np.array([[1,2,3],[2.1,4.2,6.3],[2,6,4]])
B = np.array([np.random.random(3),np.random.random(3),np.random.random(3)])
print(A)
print(np.linalg.det(A))
print(np.linalg.inv(A))
print(B)
print(np.linalg.det(B))
print(np.linalg.inv(B))
e,w = np.linalg.eig(np.linalg.inv(A)@B)
e1,w1 = sp.linalg.eig(B,A)
print(e)
print(e1)

[[1.  2.  3. ]
 [2.1 4.2 6.3]
 [2.  6.  4. ]]
1.865174681370252e-15
[[-1.12589991e+16  5.36142813e+15 -1.00000000e+00]
 [ 2.25179981e+15 -1.07228563e+15  5.00000000e-01]
 [ 2.25179981e+15 -1.07228563e+15  0.00000000e+00]]
[[0.32936918 0.31783757 0.53653211]
 [0.63684249 0.38935607 0.47111824]
 [0.15044245 0.00337018 0.51944541]]
-0.04679960107014134
[[-4.2876747   3.48915487  1.2641764 ]
 [ 5.55407999 -1.9310443  -3.98538904]
 [ 1.20576675 -0.99800483  1.5848551 ]]
[ 7.07213268e+14  4.96289336e-01 -1.45166039e-01]
[        inf+0.j  0.48713434+0.j -0.07283221+0.j]


In [19]:
S = np.copy(So)
# S[5,:] = np.array([0.28037, 0.304082, 0.308246, 0.269032, 0.287138, 0.230686])
# S[:,5] = np.array([0.28037, 0.304082, 0.308246, 0.269032, 0.287138, 0.230686])
print("original matrix:" , So)
print("Det of the orignal matrix", np.linalg.det(So))
S1 = np.linalg.inv(So)
print("inverso of the otiginal:", S1)
# print("the matrix not invertible:", S)
# print("Det of the not invert matrix", np.linalg.det(S))
# print("the inverse of the not invertible:", np.linalg.inv(S))

NameError: name 'So' is not defined

Here the distances

In [ ]:
r0 = alphas[:,0]
r1 = alphas[:,1]
r2 = alphas[:,2]
#r3 = alphas[:,3]
distances = np.array(([r0,r1,r2]))
distances = distances.transpose()
distances

### Display distances in 3D

In [ ]:
%matplotlib qt
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.set_xlabel('$d_{12}$')
ax.set_ylabel('$d_{13}$')
ax.set_zlabel('$d_{23}$')
ax.scatter(r0,r1,r2, marker='o')
plt.savefig('scatter_distances_in_3B.pdf', format='pdf', dpi=1000)

### Display distances in 2D with PCA

In [ ]:
sc = StandardScaler()
#dista = sc.fit_transform(X_train)
pca = PCA(n_components=2, svd_solver='full')
distances2D = pca.fit_transform(distances)
%matplotlib qt
plt.grid(True)
plt.xlabel('First principal component')
plt.ylabel('Second principal component')
distances2D[:,1].shape
plt.scatter(distances2D[:,0],distances2D[:,1])
plt.savefig('PCA_3B.pdf', format='pdf', dpi=1000)
var = pca.explained_variance_ratio_
var

### Display distances in 3D with PCA

In [ ]:
sc = StandardScaler()
#dista = sc.fit_transform(X_train)
pca = PCA(n_components=3, svd_solver='full')
distances3D = pca.fit_transform(distances)
%matplotlib qt
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.set_xlabel('First principal component')
ax.set_ylabel('Second principal component')
ax.set_zlabel('Third principal component')
distances3D[:,1].shape
ax.scatter(distances3D[:,0],distances3D[:,1],distances3D[:,2], marker='o')
plt.savefig('PCA_3B.pdf', format='pdf', dpi=1000)
var = pca.explained_variance_ratio_
var

### How distances spread out

In [ ]:
plt.rcParams.update({'font.size': 11})

plt.xlabel('Width gaussian parameters between first couple of particles $\sigma_{12}$')
plt.ylabel('counts')
plt.grid(True)
plt.hist(r0,bins = 40)
plt.savefig('distance_between_first_couple_of_particles.pdf', format='pdf', dpi=1000)
plt.savefig('distance_between_first_couple_of_particles.pgf', format='pgf', dpi=1000)

### How hyper--radius spreads out compared to central limit theorem

In [ ]:
hyperR = np.sqrt(r0**2 + r1**2 + r2**2)
a = 500*np.random.random(alphas.shape[0])
b = 500*np.random.random(alphas.shape[0])
c = 500*np.random.random(alphas.shape[0])
uniformGauss = np.sqrt(a**2 + b**2 + c**2)
plt.rcParams.update({'font.size': 11})
plt.xlabel('Hyper--radius $\\rho$')
plt.ylabel('counts')
plt.grid(True)
plt.hist(hyperR,bins=40, alpha=0.5, label='Hyper--radius distribution')
plt.hist(uniformGauss,bins=40, alpha=0.3, label='Addition of uniform dist')
plt.legend()
plt.savefig('graphAnr/hyper-radius.pdf', format='pdf', dpi=1000)